apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kibana
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  project: default
  source:
    chart: kibana
    repoURL: https://helm.elastic.co
    targetRevision: 7.16.3
    helm:
      parameters:
      - name: "service.type"
        value: NodePort
      - name: "service.nodePort"
        value: "30010"
