apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  project: default
  source:
    repoURL: https://fluent.github.io/helm-charts
    chart: fluentd
    targetRevision: 0.3.7
    helm:
    - values: |
        - name: varlog
          hostPath:
            path: /var/log
        - name: local1dockercontainers
          hostPath:
            path: /local1/docker/containers
        - name: etcfluentd-main
          configMap:
            name: fluentd-main
            defaultMode: 0777
        - name: etcfluentd-config
          configMap:
            name: fluentd-config
            defaultMode: 0777

        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: local1dockercontainers
          mountPath: /local1/docker/containers
          readOnly: true
        - name: etcfluentd-main
          mountPath: /etc/fluent
        - name: etcfluentd-config
          mountPath: /etc/fluent/config.d/

        fileConfigs:
          01_sources.conf: |-
            ## logs from podman
            <source>
              @type tail
              @id in_tail_container_logs
              @label @KUBERNETES
              path /var/log/containers/*.log
              pos_file /var/log/fluentd-containers.log.pos
              tag kubernetes.*
              read_from_head true    
              <parse>
                @type multi_format
                <pattern>
                  format json
                  time_key timestamp
                  keep_time_key true
                  add_newline false
                </pattern>        
                <pattern>
                  format regexp
                  expression /^(?<time>.+) (?<stream>stdout|stderr)( (.))? (?<log>.*)$/
                  time_format '%Y-%m-%dT%H:%M:%S.%NZ'
                  keep_time_key true
                </pattern>
              </parse>
              emit_unmatched_lines true
            </source>

          02_filters.conf: |-
            <label @KUBERNETES>
              <match kubernetes.var.log.containers.fluentd**>
                @type relabel
                @label @FLUENT_LOG
              </match>

              # <match kubernetes.var.log.containers.**_kube-system_**>
              #   @type null
              #   @id ignore_kube_system_logs
              # </match>

              <filter kubernetes.**>
                @type kubernetes_metadata
                @id filter_kube_metadata
                skip_labels false
                skip_container_metadata false
                skip_namespace_metadata true
                skip_master_url true
              </filter>
        
              <filter kubernetes.**>
                @type grep
                  <exclude>
                    key log
                    pattern /GET\ \/ HTTP\/1\.1/
                  </exclude>     
              </filter>
              
              <filter kubernetes.**>
                @type grep
                  <exclude>
                    key log
                    pattern /ping/
                  </exclude>     
              </filter>      

              <filter kubernetes.**>
                @type concat
                key log
                separator ""
                multiline_start_regexp  /Exception on /
                multiline_end_regexp /error.*/
              </filter>
            
            <filter kubernetes.**>
              @type parser
              key_name log
              <parse>
                @type json
                json_parser json
              </parse>
              replace_invalid_sequence true
              reserve_data true # this preserves unparsable log lines
              emit_invalid_record_to_error false # In case of unparsable log lines keep the error log clean
              reserve_time # the time was already parsed in the source, we don't want to overwrite it with current time.
            
            </filter>      

              <match **>
                @type relabel
                @label @DISPATCH
              </match>
            </label>

          03_dispatch.conf: |-
            <label @DISPATCH>
              <filter **>
                @type prometheus
                <metric>
                  name fluentd_input_status_num_records_total
                  type counter
                  desc The total number of incoming records
                  <labels>
                    tag ${tag}
                    hostname ${hostname}
                  </labels>
                </metric>
              </filter>

              <match **>
                @type relabel
                @label @OUTPUT
              </match>
            </label>

          04_outputs.conf: |-
            <label @OUTPUT>
              <match **>
                @type elasticsearch
                host "elasticsearch-master"
                port 9200
                path ""
                logstash_format true
              </match>
            </label>

                #       @type multiline
                # <pattern>
                #   format_firstline /^[a-z]*Some logs are very big/
                #   format1 /^[a-z]*Some (?<entity>) are very big in nature and hence/
                # <pattern>

                # [0-9]{4}\-[0-9]{2}\-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2} [0-9]+\.[0-9]{2}\.[0-9]+ INFO 1080 no expectation for:
