apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: efk-stack
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: efk-stack
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  project: default
  source:
    chart: elasticsearch
    repoURL: https://helm.elastic.co
    targetRevision: 7.17.3
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kibana
  namespace: efk-stack
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: efk-stack
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  project: default
  source:
    chart: kibana
    repoURL: https://helm.elastic.co
    targetRevision: 7.17.3
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent
  namespace: efk-stack
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: efk-stack
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  project: default
  source:
    repoURL: https://github.com/Debuide/efk-stack.git
    path: charts
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml

