apiVersion: argoproj.io/v1alpha1

kind: Application

metadata:

  name: samp

  namespace: dev

  finalizers:

  - resources-finalizer.argocd.argoproj.io

spec:

  destination:

    namespace: dev

    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
      prune: true
      selfHeal: true


  project: default

  source:

    path: nginx

    repoURL: https://github.com/krupakar0307/helm.git
    
    targetRevision: HEAD
